Feature/homework 13 2
DenisShishkalov/homework pull request #9
Opened 2024-07-20 11:47 UTC by DenisShishkalov

2024-07-21 06:09 UTC, painassasin requested changes

2024-07-21 06:09 UTC, painassasin commented on .idea/workspace.xml
Директорию нужно удалить с github

2024-07-21 06:09 UTC, painassasin commented on main.py
> +    global sorted_dictionary_list, mask_account_card
Зачем global?

2024-07-21 06:09 UTC, painassasin commented on main.py
> +            get_info(r"C:\Users\Денис\PycharmProjects\01\data\operations.json")
Этот путь корректно работает только на Твоей операционной системе, у любого другого будет падать с ошибкой

2024-07-21 06:09 UTC, painassasin commented on main.py
> +            from src.utils import get_info
Почему импорты не вверху файла?

2024-07-21 06:09 UTC, painassasin commented on main.py
> +def main():
Функция сильно перегружена, попробуй разбить ее на отдельные более мелкие модули

2024-07-21 06:09 UTC, painassasin commented on mylog.txt
Файл с логами на github не выкладвваем

2024-07-21 06:09 UTC, painassasin commented on pyproject.toml
> +ignore = "^0.1.4"
Для чего эта библиотека?

2024-07-21 06:09 UTC, painassasin commented on src/ascend.py
> +reader_csv_file(r"C:\Users\Денис\Downloads\transactions.csv")
Исполняемого кода не должно быть в модулях

2024-07-22 07:23 UTC, DenisShishkalov commented on pyproject.toml
> +ignore = "^0.1.4"
для чтения xlsx файла

2024-07-22 07:24 UTC, DenisShishkalov commented on src/ascend.py
> +reader_csv_file(r"C:\Users\Денис\Downloads\transactions.csv")
т.е print в модулях быть не должно?

2024-07-22 08:38 UTC, DenisShishkalov commented on main.py
> +            get_info(r"C:\Users\Денис\PycharmProjects\01\data\operations.json")
я понимаю, но как изменить, когда пишу r' ..\transactions_excel.xlsx' выбивает ошибки FileNotFoundError: [Errno 2] No such file or directory: '..\\transactions_excel.xlsx'

2024-07-23 09:05 UTC, painassasin requested changes

2024-07-23 09:05 UTC, painassasin commented on src/ascend.py
> +# print(reader_csv_file(file_transaction_csv))
Нужно удалить закомментированный код

2024-07-23 09:05 UTC, painassasin commented on src/ascend.py
> +reader_csv_file(file_transaction_csv)
Нужно удалить исполняемый код

2024-07-23 09:05 UTC, painassasin commented on src/config.py
> +current_dir = os.path.dirname(os.path.abspath(__file__))
Попробуй использовать более современную встроенную библиотеку pathlib для работы с путями
```python
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent
DATA_DIR = BASE_DIR / 'data'

file_transaction_xlsx = DATA_DIR / 'transactions_excel.xlsx'
file_transaction_csv = DATA_DIR / 'transactions.csv'
file_transaction_json = DATA_DIR / 'transactions.json'

```

2024-07-23 09:05 UTC, painassasin commented on src/filtering_by_word.py
> +path = file_transaction_json
Исполняемый код нужно удалить

2024-07-23 09:05 UTC, painassasin commented on src/main.py
Вынеси файл main.py наружу (на уровекь pyproject.toml) и сделай нормальные импорты без игнора

2024-07-23 09:05 UTC, painassasin commented on src/masks.py
> +file_handler = logging.FileHandler(r"..\logs\masks.log", "w")
Определяй путь до файла логов через путь базовой директории из src.config

2024-07-23 09:05 UTC, painassasin commented on src/masks.py
> +# get_mask_account(number="3234123412341234")
Нужно удалять закомментированный код

2024-07-23 09:05 UTC, painassasin commented on src/reader_xlsx.py
> +path = file_transaction_xlsx
Исполняемый и закооментированный код - удали его во всем проекте

2024-07-27 06:50 UTC, merged